### ISSUE TITLE
Application closed by itself while fetching data

### ISSUE THREAD

**Issue by KaoruKZ** [XezolesS/WaccaMyPageScraper#10]
Recently I received a report about not available to fetch RANKING data, the program will shut off itself when progress bar is at 53, TROPHIES and STAGE UP is working fine.

Windows 10 21H2
Scraper version: v1.1

**Comment by XezolesS** [comment]
I can't find any suspect code right now. All fetching progresses are handling their exceptions. This means this does not cause program crash.

However, I found out that if the logger has a lot of texts, the program slows down. It is perhaps the fundamental flaw of the RichTextBox control, but since the fetching task should be done only once, I thought it was okay to leave it. This might be an imposter, but the chance is very low.

Another case of crash I can think of is a connection issue. Currently, the fetcher actions check only for login status, not connecting status. If it somehow lost a connection, it could crash the program. 

This is all I can think about this issue, and it could be other one. In this weekend, I will patch the suspect above and drop a build here. If you have other details about this issue, like logs, your data from My Page, please let me know.

**Comment by XezolesS** [comment]
Try this build below.
This build allows to reconnect when the fetcher lost connection. It tries to reconnect for 10 times and if it exceeds max tries, it just cancels fetching.

I'll publish release if it resolves the issue.

[WACCA MPS 1.1.1 win-x64.zip](https://github.com/XezolesS/WaccaMyPageScraper/files/9641257/WACCA.MPS.1.1.1.win-x64.zip)
[WACCA MPS 1.1.1 win-x86.zip](https://github.com/XezolesS/WaccaMyPageScraper/files/9641258/WACCA.MPS.1.1.1.win-x86.zip)

**Comment by KaoruKZ** [comment]
By report, they could finish the fetching process, during the process they had encountered some error messages (not provided), then re-login is required by the application. Everytime they redone the process the progress bar will increase, until it's 100% done.

**Comment by KaoruKZ** [comment]
New problem: LOGIN button is not working after pasting the Aime ID.

**Comment by XezolesS** [comment]
oops, I wrote a wrong logic to prevent login after Mg Page shutdown. I'll get to home 2 hours later and fix it. 

> If you cant wait until then, you can fix it yourself by changing DateTime(2022, 9, 30) to DateTime(2022, 9, 30, 23, 59, 0) in [LoginViewModel.cs](https://github.com/XezolesS/WaccaMyPageScraper/blob/master/WaccaMyPageScraper.Wpf/ViewModels/LoginViewModel.cs#L27)

**Comment by XezolesS** [comment]
Fixed login button being disabled in: [v1.1.1 Hotfix01](https://github.com/XezolesS/WaccaMyPageScraper/releases/tag/v1.1.1-Hotfix01)

It seems all the issues have been resolved. And there's not much time left anyways, so I'm closing this issue.
